[workspace]
members = ["crates/magic-market-core", "crates/magic-tdx-rs", "crates/magic-emquant-rs", "crates/magic-tencent-rs"]
resolver = "2"
[workspace.package]
edition = "2021"
rust-version = "1.83"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Northofqing/magic-market-data-rs"
[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
[workspace.lints.rust]
unsafe_code = "forbid"
[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
