[package]
name = "magic-eastmoney-rs"
version = "0.2.0"
edition.workspace = true
license.workspace = true

[dependencies]
magic-market-core = { path = "../magic-market-core", version = "=0.2.0" }
ring = "=0.17.14"
serde = { workspace = true }
serde_json = "1"
thiserror = { workspace = true }
ureq = { version = "=2.12.1", default-features = false, features = ["tls"] }

[dev-dependencies]
time = { version = "=0.3.54", default-features = false, features = [
    "formatting",
    "std",
] }

[lints]
workspace = true
